# name: Publish
# on:
#   push:
#     branches:
#       - "main"

# concurrency: ${{ github.workflow }}-${{ github.ref }}

# permissions:
#   contents: write
#   pull-requests: write

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       #  Install Bun
#       - name: Setup Bun
#         uses: oven-sh/setup-bun@v1
#         with:
#           bun-version: latest

#       #  Cache Bun dependencies
#       - name: Cache Bun dependencies
#         uses: actions/cache@v4
#         with:
#           path: ~/.bun/install/cache
#           key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
#           restore-keys: |
#             ${{ runner.os }}-bun-

#       #  Install deps
#       - name: Install dependencies
#         run: bun install

#       #  Create Release PR or Publish
#       - name: Create Release Pull Request or Publish
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           publish: bun run release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #  Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      #  Cache Bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      #  Install deps
      - name: Install dependencies
        run: bun install

      #  Authenticate with npm
      - name: Set up npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      #  Create Release PR or Publish
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
